### ISSUE TITLE
Upload latest version to Maven Central?

### ISSUE THREAD

**Issue by timezra** [jeyben/fixedformat4j#37]
It looks like the latest version in Maven Central is 1.2.2. Do you have any plans to release the latest version there?

**Comment by jeyben** [comment]
I would like to, but haven't had the time in a while. Some sort of verification that the latest trunk/master build is stable enough to sent to the central repo would be nice.

If you have some time you are more than welcome to assist in that process.

Otherwise I will probably just wrap-up the code and call it a release.

**Comment by bbottema** [comment]
@jeyben Any update here?

**Comment by jeyben** [comment]
thanks for the ping.
I will be releasing the master branch version soon (as I said around a year ago! :-(

**Comment by jeyben** [comment]
I am working on releasing 1.4.0 to mvncentral... mean while the release can be downloaded manually
